# Generated by Django 3.2.7 on 2021-09-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_module_modulegroupmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulegroupmapping',
            name='group',
        ),
        migrations.RemoveField(
            model_name='modulegroupmapping',
            name='module',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ModuleGroupMapping',
        ),
    ]
