# Generated by Django 3.2.7 on 2021-09-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='can_create',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_destroy',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_list',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_retrieve',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='can_update',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='is_active',
        ),
        migrations.AddField(
            model_name='permission',
            name='allowed_permissions',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
