# Generated by Django 3.2.7 on 2021-09-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0003_module_can_access_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='can_access_profile',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='can_create',
            new_name='destroy',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='can_destroy',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='can_list',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='can_retrieve',
            new_name='retrieve',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='can_update',
            new_name='update',
        ),
    ]
