# Generated by Django 3.2.7 on 2021-09-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0005_otpmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='is_used',
            new_name='is_verified',
        ),
    ]
