# Generated by Django 3.2.7 on 2021-09-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0006_rename_is_used_otpmodel_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='reset_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
