# Generated by Django 3.2.7 on 2021-09-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0007_otpmodel_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
