# Generated by Django 3.2.7 on 2021-10-03 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0015_alter_otpmodel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='profile',
            new_name='profile_1',
        ),
        migrations.AddField(
            model_name='module',
            name='profile_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 12, 52, 15, 181982)),
        ),
    ]
