# Generated by Django 3.2.7 on 2021-10-03 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0016_auto_20211003_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 21, 8, 32, 993022)),
        ),
    ]
