# Generated by Django 3.2.7 on 2021-10-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('valid_days', models.IntegerField(default=7)),
                ('price', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('actual_price', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appointment_management.appointmentplan'),
            preserve_default=False,
        ),
    ]
