# Generated by Django 3.2.7 on 2021-10-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0004_auto_20211018_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentplan',
            name='discount_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
